### ISSUE TITLE
Can't run final version of code

### ISSUE THREAD

**Issue by mrfuxi** [Newmu/Theano-Tutorials#12]
Error occur when running final version of code.

``` bash
python 5_convolutional_net.py
```

Traceback

```
Traceback (most recent call last):
  File "5_convolutional_net.py", line 78, in <module>
    noise_l1, noise_l2, noise_l3, noise_l4, noise_py_x = model(X, w, w2, w3, w4, 0.2, 0.5)
  File "5_convolutional_net.py", line 44, in model
    r = conv2d(X, w, border_mode='full')
  File "/home/fuxi/.virtualenvs/deep/local/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 151, in conv2d
    return op(input, filters)
  File "/home/fuxi/.virtualenvs/deep/local/lib/python2.7/site-packages/theano/gof/op.py", line 507, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/fuxi/.virtualenvs/deep/local/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 628, in make_node
    "inputs(%s), kerns(%s)" % (_inputs.dtype, _kerns.dtype))
NotImplementedError: The image and the kernel must have the same type.inputs(float32), kerns(float64)
```

**Comment by qianguih** [comment]
This is a data type error. You can change line 68 from `X = T.ftensor4()` to`X = T.dtensor4()`. It will then work.

**Comment by palsreturn2** [comment]
Also in model function there is no parameter w_o which should have been present.

**Comment by kirk86** [comment]
even with the changes suggested by @qianguih I can't run the code example for convnet on osx. I also added theano.config.floatX='float64' at the beginning of the code.
